### ISSUE TITLE
Code Editor link invalid

### ISSUE THREAD

**Issue by e-coders** [EducatyEducate/HTML-Tutorials#1]
Whenever clicking the 'Try it yourself' link, it redirect us to the 'educational-websites.github.io' domain, which is not exist now as we deleted before. Educaty need our live code editor back.

**Comment by Genius398** [comment]
then change it

**Comment by Srinivaasan27** [comment]
@e-coders @Genius398 Should we create a new one or use the editor already created my one of the members of our organization?

**Comment by e-coders** [comment]
Guys, I will make the new code editor with new look but same functionallity.

**Comment by e-coders** [comment]
Done!
